version: "3.7"

services:
  app:
    build: './ecommerce'
    image: "cybera3s/ecommerce:app-1.0.0"
    container_name: "app"
    ports:
      - "8000"
    volumes:
      - type: 'bind'
        source: './ecommerce'
        target: '/app'
    restart: 'always'
    depends_on:
        - "postgres"

  postgres:
    container_name: 'postgres'
    image: cybera3s/ecommerce:postgres-1.0.0
    build: './postgres'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    expose:
      - '5432'
    restart: 'always'
    volumes:
      - type: 'bind'
        source: './volumes/dbdata'
        target: '/var/lib/postgresql/data'


